### ISSUE TITLE
[Tracking issue] Infrastructure for Stage 2

### ISSUE THREAD

**Issue by akashin** [near/wasmtime#159]
This is a tracking issue for all infrastructure work for Stage 2.

As our test and benchmarking suite grows, we should invest more time to make it convenient to work with them.
In an ideal world, after every change we would get a clear report of the effects on the performance and correctness of the tests - we could even generate such a report as a part of a PR request (e.g. using a CI bot).
In the same way, we need a fast local tooling that can present such a report.

```[tasklist]
- [ ] https://github.com/near/wasmtime/issues/172
- [ ] https://github.com/near/wasmtime/issues/173
- [ ] https://github.com/near/wasmtime/issues/116
```

**Comment by akashin** [comment]
I'm closing this in favor of more fine-grained tracking issues about testing and benchmarking.
