### ISSUE TITLE
[Tracking issue] Benchmarking infrastructure for Stage 2

### ISSUE THREAD

**Issue by akashin** [near/wasmtime#173]
This is a tracking issue for all tasks related to benchmarking infrastructure that we want to complete in Stage 2.

For [Stage 2](https://github.com/near/wasmtime/blob/main/docs/zkasm/roadmap.md#stage-2) we aim to support more complex WASM programs like WASM interpreter and various benchmarks. We would need tools to measure the performance of generated ZK ASM programs to help us identify opportunities for optimization.

Given the scope of the work, it might be worth writing a short design document describing how the benchmarking would work end-to-end.

```[tasklist]
- [ ] https://github.com/near/wasmtime/issues/137
- [ ] Allow benchmarks to be parameterized with input value loaded from the environment
- [ ] Introduce benchmarks that would allow us to [compare with Risc0](https://risc0.github.io/ghpages/dev/benchmarks/index.html)
```

**Comment by mooori** [comment]
## Benchmarking infra status update

- The design for the MVP was finalized in #197
- A proof of concept implementation for generating a histogram of executed instructions is available in #214.
  - The main achievement here was figuring out how to use custom helpers in `zkevm-proverjs` and how to maintain state inside them.
  - It showed that textual histogram tables would be more useful than graphs.

Steps taken to implement the generation of histogram tables of executed instructions:

- #226 adds a CLI for `run-tests-zkasm.js`. This will facilitate adding optional command line arguments for benchmarking.
- #230 adds an ISA specific setting to enable emitting calls to `zkevm-proverjs` helpers which create traces of executed instructions.
- #233 sets up the `analyze-zkasm` CLI and adds the `instrument-inst` subcommand which generates zkASM instrumented for tracing instructions executed at runtime.

## Next steps

- Finalize the zkevm-proverjs [helper](https://github.com/near/wasmtime/pull/214/files#diff-e0e611e8f6a5af71b31a8d6ec0c3c888c617d76c39f9ba303ac1c4a8393b788f) and commit it to the repo.
- Add a subcommand for running instrumented zkASM.
- Create histograms of labels executed at runtime?
- Try to generate data needed to build flame graphs?

**Comment by akashin** [comment]
Another step:
- Write down an instructions on how to generate the performance profile for all our benchmarks (sha256, fibonacci, keccak)
