### ISSUE TITLE
[Tracking issue] WASM Interpreter in ZK ASM

### ISSUE THREAD

**Issue by akashin** [near/wasmtime#174]
This is a tracking issue for all work related to selecting, compiling, and running WASM interpreter on ZKASM machine.

Our main goal for [Stage 2](https://github.com/near/wasmtime/blob/main/docs/zkasm/roadmap.md#stage-2) is to run a fully-fledged WASM interpreter on ZKASM machine. This is necessary to enable aggregatable proofs about the execution of a sequence of WASM programs (e.g. Smart-Contract calls).

This will require finding a suitable WASM interpreter, extending the set of WASM instructions supported by ZKASM backend to compile that interpreter, and testing that interpreter on a range of WASM programs and benchmarks.

We will likely need a short design doc to outline how the system will work end-to-end, from taking the code of the chosen WASM interpreter, to running a WASM program on top of ZKASM compiled version of this interpreter.

```[tasklist]
- [ ] https://github.com/near/wasmtime/issues/160
- [ ] Run WASM spectests through ZKASM-compiled interpreter
- [ ] Run benchmarks through ZKASM-compiled interpreter
```

**Comment by mooori** [comment]
At Aurora we were looking into the costs of interpreting wasm on chain. This was done in the context of [synchronous wasm execution](https://gov.near.org/t/synchronous-wasm-submodule-execution/29410). Some benchmarks are available [in this repo](https://github.com/mooori/near-interpret-wasm) where we have [a contract￼`C`](https://github.com/mooori/near-interpret-wasm/blob/main/contracts/calculations/src/lib.rs) that does number crunching in a loop. `C` is executed `natively` as NEAR contract and interpreted within another contract that contains a [wasmi](https://github.com/paritytech/wasmi) interpreter.

Some insights that could be relevant for ZK WASM are:

- Seing a possible setup for wasm interpretation on NEAR. Using wasmi it is a surprisingly smooth process.
- As the number of loop iterations is increased, the gas cost for interpreting `C` shoots up quickly, while it only slightly increases for the “native” execution. See [results](https://github.com/paritytech/wasmi) (the table can be scrolled to the right).
