### ISSUE TITLE
[Tracking issue] Software/hardware optimizations for WASM

### ISSUE THREAD

**Issue by akashin** [near/wasmtime#175]
This is a tracking issue for all performance optimizations that we aim to implement in Stage 2.

Hardware in the title refers to optimizations in ZKASM machine, for example implementing 32-bit operations. We will include them in Stage 2 depending on the rate of progress with PIL2 on Polygon side.

This will likely be an assortment of issues discovered over time during testing, benchmarking, and importing WASM interpreter.

```[tasklist]
- [ ] https://github.com/near/wasmtime/issues/162
- [ ] https://github.com/near/wasmtime/issues/151
- [ ] https://github.com/near/wasmtime/issues/144
- [ ] https://github.com/near/wasmtime/issues/105
- [ ] https://github.com/near/wasmtime/issues/158
- [ ] https://github.com/near/wasmtime/issues/181
```
